import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import NavBar from "../NavBar";
import styles from "./BaseLayout.module.css";
import { Children, useState } from "react";
type BaseLayoutProps = {
  children: React.ReactNode; // 👈️ type children
};

const BaseLayout = (props: BaseLayoutProps) => {
  let [darkMode, setDarkMode] = useState(false);
  function handleClick() {
    setDarkMode(!darkMode);
  }

  return (
    <div className={darkMode ? styles.dark : styles.light}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <div>
          <NavBar darkMode={darkMode} handleClick={handleClick} />
        </div>
        <div>{props.children}</div>
        <div>
          <footer className={styles.footer}>
            <div className="text-xs text-gray-500">
              <p>
                template created with &hearts; by{" "}
                <a href={"https://"}>Venkata Charan </a>
              </p>
              <p>&copy; 2022</p>
            </div>
          </footer>
        </div>
      </div>
    </div>
  );
};

export default BaseLayout;
